Feature/yumit
dynamicdevs/default-config-libraries pull request #4
Opened 2022-10-17 21:35 UTC by kunars

2022-10-17 21:39 UTC, PandaGO13 requested changes

2022-10-17 21:39 UTC, PandaGO13 commented on tailwind/yumit/index.js
> -      'roots-pattern': 'linear-gradient(112.78deg, #4F76FF 14.79%, #9D00E7 85.21%)'
¿ Por qué se elimina roots-pattern?

2022-10-17 21:39 UTC, PandaGO13 commented on tailwind/yumit/index.js
> +      'timeline-pattern': 'linear-gradient(12.52deg, #FDD245 50%, #FE2260 90.92%)',
Considerar ser más especifico con el nombre, ya que son configuraciones generales que se usan en varios proyectos.

2022-10-17 21:40 UTC, kunars commented on tailwind/yumit/index.js
> -      'roots-pattern': 'linear-gradient(112.78deg, #4F76FF 14.79%, #9D00E7 85.21%)'
Porque ese roots pattern no lo necesitamos en yumit, se está creando otra carpeta de configuración solo para yumit.

2022-10-17 21:41 UTC, kunars commented on tailwind/yumit/index.js
> +      'timeline-pattern': 'linear-gradient(12.52deg, #FDD245 50%, #FE2260 90.92%)',
En este caso es solo para yumit.

2022-10-17 21:45 UTC, PandaGO13 approved these changes

2022-10-18 16:49 UTC, c1sar approved these changes

2022-10-18 16:50 UTC, merged